services:
  votc:
    build: .
    container_name: votc
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.votc.rule=Host(`votc.jeffemmett.com`)"
      - "traefik.http.services.votc.loadbalancer.server.port=3000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
